export const AddressSeeds = [
  {
    street_number: "1234",
    street_name: "Main Street",
    city: "Dallas",
    state: "Texas",
    zip_code: "75227",
    personId: 1,
  },
  {
    street_number: "4545",
    street_name: "Second Ave.",
    city: "Sacramento",
    state: "California",
    zip_code: "95824",
    personId: 2,
  },
  {
    street_number: "9999",
    street_name: "Sunday Lane",
    city: "Dallas",
    state: "Texas",
    zip_code: "99880",
    personId: 3,
  },
  {
    street_number: "4545",
    street_name: "Broadway",
    city: "New York",
    state: "New York",
    zip_code: "12123",
    personId: 4,
  },
  {
    street_number: "9999",
    street_name: "Beach Drive",
    city: "New York",
    state: "New York",
    zip_code: "34543",
    personId: 5,
  },
  {
    street_number: "unknown",
    street_name: "unknown",
    city: "Asgard",
    state: "Asgard",
    zip_code: "unknown",
    personId: 6,
  },
  {
    street_number: "8795",
    street_name: "Wall Street",
    city: "New York",
    state: "New York",
    zip_code: "34543",
    personId: 7,
  },
  {
    street_number: "unknown",
    street_name: "unknown",
    city: "unknown",
    state: "unknown",
    zip_code: "unknown",
    personId: 8,
  },
  {
    street_number: "4562",
    street_name: "Berry Lane",
    city: "Queens",
    state: "New York",
    zip_code: "77312",
    personId: 9,
  },
  {
    street_number: "31245",
    street_name: "Palisades Drive",
    city: "New York",
    state: "New York",
    zip_code: "98454",
    personId: 10,
  },
  {
    street_number: "9090",
    street_name: "spidey drive",
    city: "New York",
    state: "New York",
    zip_code: "88787",
    personId: 11,
  },
  {
    street_number: "12345",
    street_name: "wayne manor drive",
    city: "Gotham",
    state: "New York",
    zip_code: "45220",
    personId: 12,
  },
  {
    street_number: "8451",
    street_name: "daily planet street",
    city: "Metropolis",
    state: "New Jersey",
    zip_code: "33333",
    personId: 13,
  },
  {
    street_number: "5445",
    street_name: "prince drive",
    city: "Capitol city",
    state: "Thermascyra",
    zip_code: "99999",
    personId: 14,
  },
  {
    street_number: "8887",
    street_name: "Trident avenue",
    city: "Poseidonis",
    state: "Atlantis",
    zip_code: "1111",
    personId: 15,
  },
  {
    street_number: "4567",
    street_name: "Quick street",
    city: "Gotham",
    state: "New York",
    zip_code: "75112",
    personId: 16,
  },
];
