export const AddressSeeds = [
  {
    street_number: "1234",
    street_name: "Main Street",
    city: "Dallas",
    state: "Texas",
    zip_code: "75227",
    personId: 1,
  },
  {
    street_number: "4545",
    street_name: "Second Ave.",
    city: "Sacramento",
    state: "California",
    zip_code: "95824",
    personId: 2,
  },
  {
    street_number: "9999",
    street_name: "Sunday Lane",
    city: "Dallas",
    state: "Texas",
    zip_code: "99880",
    personId: 3,
  },
  {
    street_number: "4545",
    street_name: "Broadway",
    city: "New York",
    state: "New York",
    zip_code: "12123",
    personId: 4,
  },
  {
    street_number: "9999",
    street_name: "Beach Drive",
    city: "New York",
    state: "New York",
    zip_code: "34543",
    personId: 5,
  },
  {
    street_number: "unknown",
    street_name: "unknown",
    city: "Asgard",
    state: "Asgard",
    zip_code: "unknown",
    personId: 6,
  },
  {
    street_number: "8795",
    street_name: "Wall Street",
    city: "New York",
    state: "New York",
    zip_code: "34543",
    personId: 7,
  },
  {
    street_number: "unknown",
    street_name: "unknown",
    city: "unknown",
    state: "unknown",
    zip_code: "unknown",
    personId: 8,
  },
  {
    street_number: "4562",
    street_name: "Berry Lane",
    city: "Queens",
    state: "New York",
    zip_code: "77312",
    personId: 9,
  },
  {
    street_number: "31245",
    street_name: "Palisades Drive",
    city: "Gptham City",
    state: "New York",
    zip_code: "98454",
    personId: 10,
  },
];
